=== vivekNarayanan/JsonObjectMapper/src/schema/StaffSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/StaffSchema"
	xmlns:tns="http://www.example.org/StaffSchema"
	xmlns:skills="http://www.example.org/skills"
	elementFormDefault="qualified">
	<import schemaLocation="skills.xsd" namespace="http://www.example.org/skills"/>
	<element name="followUp">
		<complexType>
			<sequence>
				<element name="staffData" type="tns:staff" minOccurs="1"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>
	<complexType name="staff">
		<sequence>
			<element name="name" type="string"/>
			<element name="age" type="string"/>
			<element name="position" type="string"/>
			<element name="salary" type="string" minOccurs="1" />
			<element name="skills" type="skills:skill" minOccurs="1" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
</schema>

=== vivekNarayanan/JsonObjectMapper/src/schema/StaffSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:followUp xmlns:tns="http://www.example.org/StaffSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/StaffSchema StaffSchema.xsd ">
  <tns:staffData>
    <tns:name>vivek</tns:name>
    <tns:age>35</tns:age>
    <tns:position>Quater Back</tns:position>
    <tns:salary>100,000</tns:salary>
    <tns:skills>Running to the Base</tns:skills>
    <tns:skills>Running to the Base 2</tns:skills>
  </tns:staffData>
</tns:followUp>
